# 1. Impor Library

In [1]:
#mengimpor library yang diperlukan
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

# 2. Baca Dataset

In [2]:
#membaca dataset
df=pd.read_csv('https://raw.githubusercontent.com/yyunitasa-stack/Amazon-E-Commerce-Sales-Performance-Analysis/main/Dataset/Amazon%20Sale%20Report.csv')

C:\Users\YUNITA\AppData\Local\Temp\ipykernel_24152\1976285538.py:2: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('https://raw.githubusercontent.com/yyunitasa-stack/Amazon-E-Commerce-Sales-Performance-Analysis/main/Dataset/Amazon%20Sale%20Report.csv')

# 3. Data Inspection

In [3]:
#menampilkan 5 data teratas
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [4]:
#memeriksa ukuran dataset
df.shape
#Interpretasi: Dataset memiliki 128.975 baris dan 10 kolom

(128975, 24)

In [5]:
#memeriksa informasi dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  str
 2   Date                128975 non-null  str
 3   Status              128975 non-null  str
 4   Fulfilment          128975 non-null  str
 5   Sales Channel       128975 non-null  str
 6   ship-service-level  128975 non-null  str
 7   Style               128975 non-null  str
 8   SKU                 128975 non-null  str
 9   Category            128975 non-null  str
 10  Size                128975 non-null  str
 11  ASIN                128975 non-null  str
 12  Courier Status      122103 non-null  str
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  str
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  str
 17  ship-state          128942 non-null  str
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  str
 20  promotion-ids       79822 non-null   str
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   str
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(1), str(18)
memory usage: 22.8+ MB

In [6]:
#menampilkan statistik deskriptif dari dataset
df.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

# 4. Data Preparation

## 4.1 Column & Data Type

In [7]:
#memeriksa nama-nama kolom
print(df.columns.tolist())
#Interpetasi: terdapat whitespace pada nama kolom Sales Channel
#Interpretasi: nama kolom tidak konsisten (kapital dan kecil) sehingga perlu diatasi

['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ', 'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'B2B', 'fulfilled-by', 'Unnamed: 22']

In [8]:
#mengatasi nama kolom yang tidak konsisten dan mengandung whitespace
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.columns=df.columns.str.replace('-','_')
df = df.rename(columns={
    'sales_channel_': 'sales_channel',
    'sku': 'SKU',
    'asin': 'ASIN',
    'b2b': 'B2B',
    'unnamed:_22':'unnamed:22'
})

In [9]:
df.columns

Index(['index', 'order_id', 'date', 'status', 'fulfilment', 'sales_channel',
       'ship_service_level', 'style', 'SKU', 'category', 'size', 'ASIN',
       'courier_status', 'qty', 'currency', 'amount', 'ship_city',
       'ship_state', 'ship_postal_code', 'ship_country', 'promotion_ids',
       'B2B', 'fulfilled_by', 'unnamed:22'],
      dtype='str')

In [10]:
#menampilkan 5 data teratas
df.head()
#Interpretasi: Kolom currency, ship_country, dan fulfilled_by memiliki nilai yang konstan sehingga tidak memiliki arti analisis
#Interpretasi: Kolom index memiliki nilai yang unik sehingga tidak memiliki arti analisis
#Interpretasi: Kolom style, SKU, ship_postal_code, ASIN, dan promotion_ids tidak memiliki arti analisis karena merupakan identifier unik dari setiap transaksi

,index,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,SKU,category,...,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,B2B,fulfilled_by,unnamed:22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [11]:
#menghapus kolom konstan dan kolom yang tidak memiliki arti analisis
df.drop(['index','currency','ship_country','unnamed:22','style','SKU','ship_postal_code','ASIN','promotion_ids','fulfilled_by'],axis=1,inplace=True)

In [12]:
#memeriksa tipe data dari setiap kolom
df.dtypes
#Interpretasi: Tipe data date adalah string, sehingga perlu diubah menjadi tipe data datetime agar dapat dilakukan analisis berbasis waktu
#Interpretasi: Tipe data ship_postal_code adalah float, sehingga perlu diubah menjadi tipe data string/object karena berfungsi sebagai kode atau identitas

order_id                  str
date                      str
status                    str
fulfilment                str
sales_channel             str
ship_service_level        str
category                  str
size                      str
courier_status            str
qty                     int64
amount                float64
ship_city                 str
ship_state                str
B2B                      bool
dtype: object

In [13]:
#menangani kolom date dengan mengubah menjadi tipe data datetime
df['date'] = pd.to_datetime(
    df['date'],
    format='%m-%d-%y',
    errors='coerce'
)

## 4.2 Data Quality Check

### a. Nilai Tidak Konsisten dan Whitespace

In [14]:
#memeriksa data yang tidak konsisten pada variabel status
df['status'].value_counts()
#interpretasi: tidak ada data pada variabel Status yang tidak konsisten

status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [15]:
#memeriksa data yang tidak konsisten pada variabel Fulfilment
df['fulfilment'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

fulfilment
Amazon      89698
Merchant    39277
Name: count, dtype: int64

In [16]:
#memeriksa data yang tidak konsisten pada variabel Sales Channel
df['sales_channel'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

sales_channel
Amazon.in     128851
Non-Amazon       124
Name: count, dtype: int64

In [17]:
#memeriksa data yang tidak konsisten pada variabel ship-service-level
df['ship_service_level'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

ship_service_level
Expedited    88615
Standard     40360
Name: count, dtype: int64

In [18]:
#memeriksa data yang tidak konsisten pada variabel category
df['category'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [19]:
#memeriksa data yang tidak konsisten pada variabel size
df['size'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

size
M       22711
L       22132
XL      20876
XXL     18096
S       17090
3XL     14816
XS      11161
6XL       738
5XL       550
4XL       427
Free      378
Name: count, dtype: int64

In [20]:
#memeriksa data yang tidak konsisten pada variabel Courier Status
df['courier_status'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

courier_status
Shipped      109487
Unshipped      6681
Cancelled      5935
Name: count, dtype: int64

In [21]:
#memeriksa data yang tidak konsisten pada variabel ship-city
df['ship_city'].value_counts()
#interpretasi: kolom ship-city memiliki banyak data yang salah sehingga perlu dihapus

ship_city
BENGALURU                    11217
HYDERABAD                     8074
MUMBAI                        6126
NEW DELHI                     5795
CHENNAI                       5421
                             ...
VARANASIVaranasi                 1
Cherukunnu (p.o)                 1
GULABPURA, Distt BHILWARA        1
Prayagraj (ALLAHABAD)            1
Halol                            1
Name: count, Length: 8955, dtype: int64

In [22]:
#memeriksa data yang tidak konsisten pada variabel ship-state
df['ship_state'].value_counts()
#interpretasi: terdapat data yang tidak konsisten

ship_state
MAHARASHTRA      22260
KARNATAKA        17326
TAMIL NADU       11483
TELANGANA        11330
UTTAR PRADESH    10638
                 ...
Nagaland             1
bihar                1
Mizoram              1
rajsthan             1
Rajsthan             1
Name: count, Length: 69, dtype: int64

### b. Nilai Tidak Valid

In [23]:
#memeriksa invalid values pada setiap kolom numerik
df.describe()
#Interpretasi: tidak terdapat invalid values pada setiap kolom numerik

                             date            qty         amount
count                      128975  128975.000000  121180.000000
mean   2022-05-12 11:49:27.951929       0.904431     648.561465
min           2022-03-31 00:00:00       0.000000       0.000000
25%           2022-04-20 00:00:00       1.000000     449.000000
50%           2022-05-10 00:00:00       1.000000     605.000000
75%           2022-06-04 00:00:00       1.000000     788.000000
max           2022-06-29 00:00:00      15.000000    5584.000000
std                           NaN       0.313354     281.211687

### c. Duplicate Data

In [24]:
#menampilkan duplicate data
df.duplicated().sum()
#interpretasi: terdapat 6 data duplikat

np.int64(785)

In [25]:
#memeriksa setiap baris yang memiliki duplikat
df[df.duplicated(keep=False)]

,order_id,date,status,fulfilment,sales_channel,ship_service_level,category,size,courier_status,qty,amount,ship_city,ship_state,B2B
166,407-3742007-3242711,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,kurta,S,Shipped,1,517.0,HYDERABAD,TELANGANA,False
167,407-3742007-3242711,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,kurta,S,Shipped,1,517.0,HYDERABAD,TELANGANA,False
306,408-3870331-6287517,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,kurta,L,Shipped,1,399.0,Dehradun,UTTARAKHAND,False
307,408-3870331-6287517,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,kurta,L,Shipped,1,399.0,Dehradun,UTTARAKHAND,False
365,403-7042175-3905937,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,kurta,M,Shipped,1,499.0,BARRACKPORE,WEST BENGAL,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128495,406-7346635-7865146,2022-06-01,Shipped,Amazon,Amazon.in,Expedited,kurta,XL,Shipped,1,292.0,BENGALURU,KARNATAKA,False
128907,403-6757403-6097100,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,Set,3XL,Cancelled,0,NaN,GREATER NOIDA,UTTAR PRADESH,False
128908,403-6757403-6097100,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,Set,3XL,Cancelled,0,NaN,GREATER NOIDA,UTTAR PRADESH,False
128952,404-8878574-4524358,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,kurta,M,Shipped,1,301.0,Rishra Hooghly,WEST BENGAL,False
128953,404-8878574-4524358,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,kurta,M,Shipped,1,301.0,Rishra Hooghly,WEST BENGAL,False

### d. Missing Value

In [26]:
#memeriksa missing value pada dataset
df.isnull().sum()
#interpretasi: kolom courier-status, amount, ship-city, ship-state, ship-postal-code, promotion-ids memiliki missing value

order_id                 0
date                     0
status                   0
fulfilment               0
sales_channel            0
ship_service_level       0
category                 0
size                     0
courier_status        6872
qty                      0
amount                7795
ship_city               33
ship_state              33
B2B                      0
dtype: int64

In [27]:
#memeriksa persentase missing value
df.isnull().sum()/df.shape[0]*100
#Interpretasi: kolom ship_city dan ship_state memiliki missing value kurang dari 5% (<5%), sehingga baris berisi missing value bisa langsung dihapus (drop)

order_id              0.000000
date                  0.000000
status                0.000000
fulfilment            0.000000
sales_channel         0.000000
ship_service_level    0.000000
category              0.000000
size                  0.000000
courier_status        5.328164
qty                   0.000000
amount                6.043807
ship_city             0.025586
ship_state            0.025586
B2B                   0.000000
dtype: float64

In [28]:
#menampilkan detail baris dan kolom missing value
df[df.isnull().any(axis=1)]

,order_id,date,status,fulfilment,sales_channel,ship_service_level,category,size,courier_status,qty,amount,ship_city,ship_state,B2B
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,Set,S,NaN,0,647.62,MUMBAI,MAHARASHTRA,False
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,Western Dress,L,NaN,0,753.33,PUDUCHERRY,PUDUCHERRY,False
8,407-5443024-5233168,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,Set,3XL,Cancelled,0,NaN,HYDERABAD,TELANGANA,False
23,404-6019946-2909948,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,Set,M,NaN,0,570.48,pune,MAHARASHTRA,False
29,404-5933402-8801952,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,kurta,3XL,NaN,0,NaN,GUWAHATI,ASSAM,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128903,406-3923120-4345139,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,kurta,M,Cancelled,0,NaN,ANANTAPUR,ANDHRA PRADESH,False
128907,403-6757403-6097100,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,Set,3XL,Cancelled,0,NaN,GREATER NOIDA,UTTAR PRADESH,False
128908,403-6757403-6097100,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,Set,3XL,Cancelled,0,NaN,GREATER NOIDA,UTTAR PRADESH,False
128958,408-9513596-4393945,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,Set,L,Cancelled,0,NaN,Bengaluru,KARNATAKA,False
128967,404-5182288-1653947,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,kurta,XS,Cancelled,0,NaN,Kolkata,WEST BENGAL,False

## 4.3 Data Cleaning

### a. Mengatasi Nilai Tidak Konsisten

In [29]:
#mengatasi data tidak konsisten
df['ship_state']=df['ship_state'].str.upper()
df['ship_state'] = df['ship_state'].replace({
    'ORISSA': 'ODISHA',
    'RJ': 'RAJASTHAN',
    'RAJSHTHAN': 'RAJASTHAN',
    'RAJSTHAN': 'RAJASTHAN',
    'NL': 'NAGALAND',
    'PUNJAB/MOHALI/ZIRAKPUR': 'PUNJAB',
    'PB': 'PUNJAB',
    'APO': 'ANDHRA PRADESH',
    'AR': 'ARUNACHAL PRADESH',
    'PONDICHERRY': 'PUDUCHERRY',
    'NEW DELHI': 'DELHI'
})
#menghapus kolom ship-city, karena banyak nilai yang salah pada kolom tersebut
df.drop(['ship_city'],axis=1,inplace=True)

### b. Mengatasi Duplicate Data

In [30]:
#mengatasi data duplikat dengan menghapus salah satu baris duplikat
df.drop_duplicates(inplace=True)

### c. Mengatasi Missing Value

In [31]:
#menghapus baris yang berisi missing value <5% (ship-city)
df.dropna(subset='ship_state', inplace=True)
#mengatasi missing value dengan mengisi menggunakan modus pada kolom Courier Status
df['courier_status']=df['courier_status'].fillna(df['courier_status'].mode()[0])
#mengatasi missing value dengan mengisi menggunakan median pada kolom Amount
df['amount']=df['amount'].fillna(df['amount'].median())

## 4.4 Data Validation

In [32]:
#memeriksa kembali kolom dan tipe data
df.dtypes
#Interpretasi: nama kolom dan tipe data masing-masing kolom sudah sesuai

order_id                         str
date                  datetime64[us]
status                           str
fulfilment                       str
sales_channel                    str
ship_service_level               str
category                         str
size                             str
courier_status                   str
qty                            int64
amount                       float64
ship_state                       str
B2B                             bool
dtype: object

In [33]:
#memeriksa kembali data konsisten
df['ship_state'].value_counts()
#data sudah konsisten

ship_state
MAHARASHTRA           22131
KARNATAKA             17219
TAMIL NADU            11390
TELANGANA             11254
UTTAR PRADESH         10604
DELHI                  7013
KERALA                 6522
WEST BENGAL            5923
ANDHRA PRADESH         5383
GUJARAT                4461
HARYANA                4396
RAJASTHAN              2703
MADHYA PRADESH         2510
ODISHA                 2129
BIHAR                  2106
PUNJAB                 1910
ASSAM                  1658
UTTARAKHAND            1543
JHARKHAND              1449
GOA                    1134
CHHATTISGARH            905
HIMACHAL PRADESH        783
JAMMU & KASHMIR         700
PUDUCHERRY              347
CHANDIGARH              332
MANIPUR                 312
ANDAMAN & NICOBAR       257
MEGHALAYA               204
SIKKIM                  204
NAGALAND                187
TRIPURA                 151
ARUNACHAL PRADESH       146
MIZORAM                  75
DADRA AND NAGAR          70
LADAKH                   43
LAKSHADWEEP               4
Name: count, dtype: int64

In [34]:
#memeriksa kembali data duplikat
df.duplicated().sum()
#data sudah tidak ada duplikat

np.int64(0)

In [35]:
#memeriksa kembali missing value
df.isnull().sum()
#data sudah tidak ada missing value

order_id              0
date                  0
status                0
fulfilment            0
sales_channel         0
ship_service_level    0
category              0
size                  0
courier_status        0
qty                   0
amount                0
ship_state            0
B2B                   0
dtype: int64

In [36]:
#menyimpan dataset yang sudah dibersihkan ke dalam file CSV
df.to_csv("C:/Users/YUNITA/Documents/GitHub/Amazon E Commerce Sales Performance Analysis/Dataset/Amazon Sale Report Cleaned.csv",index=False)